const marketplace = artifacts.require("./Marketplace.sol");

const increaseTime = function(duration) {
  const id = Date.now()

  return new Promise((resolve, reject) => {
    web3.currentProvider.sendAsync({
      jsonrpc: '2.0',
      method: 'evm_increaseTime',
      params: [duration],
      id: id,
    }, err1 => {
      if (err1) return reject(err1)

      web3.currentProvider.sendAsync({
        jsonrpc: '2.0',
        method: 'evm_mine',
        id: id+1,
      }, (err2, res) => {
        return err2 ? reject(err2) : resolve(res)
      })
    })
  })
}

contract('marketplace test', async (accounts) => {
	it("shoud add 5 product and check his id generated by keccak-256", async () => {
		let ins = await marketplace.deployed();

		let id = await ins.newProduct.call("testid",1000,1000);

        assert.equal(id.valueOf(), "0x4b622b86e78c8e4f741ba1b74c587b54effcf7e44ba90876e00bb845ca741530");
        id = await ins.newProduct.call("test1",1,1000);
        assert.equal(id.valueOf(), "0x6d255fc3390ee6b41191da315958b7d6a1e5b17904cc7683558f98acc57977b4");
        id = await ins.newProduct.call("test2",2,2000);
        assert.equal(id.valueOf(), "0x4da432f1ecd4c0ac028ebde3a3f78510a21d54087b161590a63080d33b702b8d");
        id = await ins.newProduct.call("test3",3,3000);
        assert.equal(id.valueOf(), "0x204558076efb2042ebc9b034aab36d85d672d8ac1fa809288da5b453a4714aae");
        id = await ins.newProduct.call("test4",4,4000);
	})
	
	/*it("should buy presale tokens", async () => {
		let ins = await marketplace.deployed();
		
		var acc = accounts[0];
		
		await ins.buy({from: acc, value: web3.toWei(3500, "finney")});
					 
		let tokenBal = await ins.allowance(ins.address, acc);

		assert.equal(tokenBal, 3);
	})
	
	it("should buy marketplace tokens", async () => {
		let ins = await marketplace.deployed();
		
		await increaseTime(60*62);
		
		var acc = accounts[1];
		
		await ins.buy({from: acc, value: web3.toWei(4500, "finney")});
					 
		let tokenBal = await ins.allowance(ins.address, acc);

		assert.equal(tokenBal, 2);
	})
	
	it("should block transfer", async () => {
		let ins = await marketplace.deployed();
		
		try{
			await ins.transfer("0x123", "3");
			assert(true, "");
		} catch(e) {
			return;
		}
		
		assert(false, "transfer is not blocked");
	})
	
	it("should block transferFrom", async () => {
		let ins = await marketplace.deployed();
		
		try{
			await ins.transferFrom(ins.address, "0x123", "3");
			assert(true, "");
		} catch(e) {
			return;
		}
		
		assert(false, "transferFrom is not blocked");
	})
	
	it("should block approve", async () => {
		let ins = await marketplace.deployed();
		
		try{
			await ins.approve("0x123", "3");
			assert(true, "");
		} catch(e) {
			return;
		}
		
		assert(false, "approve is not blocked");
	})
	
	it("should withdraw tokens", async () => {
		let ins = await marketplace.deployed();
		
		await increaseTime(122*60);
		
		var acc = accounts[0];
		
		await ins.transferFrom(ins.address, acc, 3);
		
		let bal = await ins.balanceOf(acc);
		
		assert.equal(bal.valueOf(), 3, "the withdraw didn't happen");
	})
	
	it("should transfer tokens", async () => {
		let ins = await marketplace.deployed();
		
		var acc = accounts[0];
		var acc2 = accounts[2];
		
		let bal1 = await ins.balanceOf(acc);
		
		let bal2 = await ins.balanceOf(acc2);
		
		await ins.transfer(acc2, 2, {from: acc});
		
		let bal1_after = await ins.balanceOf(acc);
		let bal2_after = await ins.balanceOf(acc2);
		
		assert.equal(bal1.sub(2).valueOf(), bal1_after.valueOf(), "The transfer didn't happen");
		assert.equal(bal2.add(2).valueOf(), bal2_after.valueOf(), "The transfer didn't happen");
	})*/
})